### ISSUE TITLE
Nie działające locale

### ISSUE THREAD

**Issue by olimplan** [kyob/LMSTauronPowerOutagesPlugin#2]
z tego co widzę, w locale jest tłumaczenie 'emergency', natomiast mam taki efekt:
![Zrzut ekranu z 2020-06-06 08-33-58](https://user-images.githubusercontent.com/17432641/83937940-2640b600-a7d1-11ea-8c90-b0a71df52a5a.png)

**Comment by kyob** [comment]
Dzięki.

**Comment by olimplan** [comment]
Dzięki za poprawkę, teraz działa poprawnie:
![Zrzut ekranu z 2020-06-06 10-15-46](https://user-images.githubusercontent.com/17432641/83939639-c51fdf00-a7de-11ea-80ea-5db5c7adf6a3.png)
I przy okazji widzę, że dodałeś obsługę kilku powiatów :-) BARDZO DZIĘKUJĘ :-)
