### ISSUE TITLE
Nie działa obsługa kilku powiatów

### ISSUE THREAD

**Issue by olimplan** [kyob/LMSTauronPowerOutagesPlugin#3]
Konfiguracja zrobiona tak (województwo małopolskie, powiat wielicki - gaid=950, powiat myślenicki - gaid=940):
![Zrzut ekranu z 2020-06-08 11-54-59](https://user-images.githubusercontent.com/17432641/84017609-326a7600-a97f-11ea-9403-90e7409a4952.png)
Wynik:
![Zrzut ekranu z 2020-06-08 11-55-09](https://user-images.githubusercontent.com/17432641/84017635-3d250b00-a97f-11ea-8cb3-79790e7d19c1.png)
I to się zgadza - dzisiaj akurat w powiecie myślenickim nie ma żadnych ani awaryjnych ani planowych wyłaczeń, w powiecie wielickim są.
Natomiast jak zmienię kolejność w _**tauron.district**_ z 950,940 na 940,950, wyświetla się:
![Zrzut ekranu z 2020-06-08 11-55-34](https://user-images.githubusercontent.com/17432641/84017804-79586b80-a97f-11ea-848e-a0384f1fdca2.png)
Wygląda, jakby wyświetlany był wynik tylko dla pierwszego district.

**Comment by kyob** [comment]
Dzięki za zgłoszenie. Poprawione.

**Comment by olimplan** [comment]
Niestety nadal działa tak samo :(

**Comment by kyob** [comment]
Poprawiłem teraz w obu miejscach i powinna działać.

**Comment by olimplan** [comment]
Potwierdzam, teraz jest OK :-)
