### ISSUE TITLE
Plugin nie działa w lms+ stable (25.x)

### ISSUE THREAD

**Issue by olimplan** [kyob/LMSTauronPowerOutagesPlugin#4]
Aktualne stable (świeżynka ;) ), wrzuciłem aktualny plugin (HEAD), opcje konfiguracyjne są ustawione jak w działającym pluginie na stable-24. Efekt - nie wyświetla się nic, natomiast w error.log ląduje:

PHP Warning:  array_merge_recursive(): Expected parameter 2 to be an array, null given in /var/www/lms.git/plugins/LMSTauronPowerOutagesPlugin/modules/tauronpoweroutages.php on line 20
PHP Warning:  array_merge_recursive(): Expected parameter 1 to be an array, null given in /var/www/lms.git/plugins/LMSTauronPowerOutagesPlugin/modules/tauronpoweroutages.php on line 27
PHP Warning:  array_merge_recursive(): Expected parameter 1 to be an array, null given in /var/www/lms.git/plugins/LMSTauronPowerOutagesPlugin/modules/tauronpoweroutages.php on line 27

PHP w wersji 7.4.

**Comment by kyob** [comment]
Podaj swoje opcje konfiguracyjne, bo u mnie działa :)

**Comment by olimplan** [comment]
W dniu pią, 20.11.2020 o godzinie 04∶09 -0800, użytkownik
kyob napisał:
> Podaj swoje opcje konfiguracyjne, bo u mnie działa :)
> 
> 
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or
> unsubscribe.

tauron.api_url = 
https://www.tauron-dystrybucja.pl/iapi/tauron.district
= 940,950
		
z dokładnie tymi samymi opcjami (ale ciut starsza wersja
pluginu, bo dawno nie robiłem git pulla) na stable-24 24.48
śmiga.
-- 
Jacek Rzęsista
Olimplan
ul. Sikorskiego 73
32-400 Myślenice

**Comment by kyob** [comment]
Sam sobie odpowiedziałeś. Sprawdzć sekcje **[Configuration](https://github.com/kyob/LMSTauronPowerOutagesPlugin)**

@olimplan 
> bo dawno nie robiłem git pulla

**Comment by olimplan** [comment]
> Sam sobie odpowiedziałeś. Sprawdzć sekcje **[Configuration](https://github.com/kyob/LMSTauronPowerOutagesPlugin)**
> 
> @olimplan
> 
> > bo dawno nie robiłem git pulla

Hmm wygląda na to, że w mailu zjadło enter w formatowaniu ;)
Mam dokładnie tak:
tauron.api_url = https://www.tauron-dystrybucja.pl/iapi/
tauron.district = 940,950
Patrzę na sekcję configuration i jedyne róznice które widzę, to:
- brak tauron.commune - ale przecież nie jest konieczny ? :-)
- w opisie masz literówkę - jest "taruron.api_url" zamiast "tauron.api_url"
Innych różnic nie widzę :(

**Comment by kyob** [comment]
PHP 7.3.24 
![Screenshot_2020-11-20  LMS ](https://user-images.githubusercontent.com/689112/99810714-6825a480-2b44-11eb-9f80-1f7840f84f97.png)
![Screenshot_2020-11-20 LMS Konfiguracja interfejsu użytkownika](https://user-images.githubusercontent.com/689112/99810716-68be3b00-2b44-11eb-87b5-ca0f1598077e.png)

Jak znajdę chwilę wolnego dorobię obsługę błędów. Może coś się więcej dowiemy.

**Comment by olimplan** [comment]
U mnie wygląda to tak:
![Zrzut ekranu z 2020-11-20 15-47-29](https://user-images.githubusercontent.com/17432641/99813381-e46db700-2b47-11eb-979a-7f49f4b5405f.png)
![Zrzut ekranu z 2020-11-20 15-48-02](https://user-images.githubusercontent.com/17432641/99813409-eafc2e80-2b47-11eb-9269-b244468a6834.png)

**Comment by olimplan** [comment]
a wersja PHP:
php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

(Ubuntu 20.04)

**Comment by kyob** [comment]
Masz zainstalowanego curla?
```bash
php -r 'var_dump(extension_loaded("curl"));'
Command line code:1:
bool(true)
```

**Comment by olimplan** [comment]
a wersja PHP:
php -v
PHP 7.4.3 (cli) (built: Oct  6 2020 15:47:56) ( NTS )
Copyright (c) The PHP Group
Zend Engine v3.4.0, Copyright (c) Zend Technologies
    with Zend OPcache v7.4.3, Copyright (c), by Zend Technologies

(Ubuntu 20.04)

> Masz zainstalowanego curla?
> 
> ```shell
> php -r 'var_dump(extension_loaded("curl"));'
> Command line code:1:
> bool(true)
> ```



dpkg -l | grep curl
ii  curl                              7.68.0-1ubuntu2.2                 amd64        command line tool for transferring data with URL syntax
ii  libcurl3-gnutls:amd64         7.68.0-1ubuntu2.2                 amd64        easy-to-use client-side URL transfer library (GnuTLS flavour)
ii  libcurl4:amd64                7.68.0-1ubuntu2.2                 amd64        easy-to-use client-side URL transfer library (OpenSSL flavour)
ii  php-curl                      2:7.4+75                          all          CURL module for PHP [default]
ii  php7.4-curl                   7.4.3-4ubuntu2.4                  amd64        CURL module for PHP
root@pmx-lms:~# php -r 'var_dump(extension_loaded("curl"));'
bool(true)

Jest curl i php-curl :-)

**Comment by kyob** [comment]
Możesz pobrać aktualną wersję i zweryfikować?

**Comment by olimplan** [comment]
Jest komunikat o błędzie:
![Zrzut ekranu z 2020-11-25 10-54-11](https://user-images.githubusercontent.com/17432641/100211622-a6d4a980-2f0c-11eb-828e-3b5b81435663.png)
wygląda na problem curla z SSL-em. Zapewne coś mam niezainstalowane ... ;) Niestety nie mam pomysłu co ...

**Comment by kyob** [comment]
Ja mam Centosa:
```bash
# openssl version -a
OpenSSL 1.0.2k-fips  26 Jan 2017
built on: reproducible build, date unspecified
platform: linux-x86_64
options:  bn(64,64) md2(int) rc4(8x,char) des(idx,cisc,16,int) idea(int) blowfish(idx) 
compiler: gcc -I. -I.. -I../include  -fPIC -DOPENSSL_PIC -DZLIB -DOPENSSL_THREADS -D_REENTRANT -DDSO_DLFCN -DHAVE_DLFCN_H -DKRB5_MIT -m64 -DL_ENDIAN -Wall -O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic -Wa,--noexecstack -DPURIFY -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DRC4_ASM -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DWHIRLPOOL_ASM -DGHASH_ASM -DECP_NISTZ256_ASM
OPENSSLDIR: "/etc/pki/tls"
engines:  dynamic 
```

**Comment by olimplan** [comment]
u mnie wygląda to tak:
- LMS stable 24.x, Ubuntu 18.04:
# openssl version -a
OpenSSL 1.1.1  11 Sep 2018
built on: Wed May 27 19:15:54 2020 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-dyPhHZ/openssl-1.1.1=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAES_ASM -DVPAES_ASM -DBSAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPADLOCK_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific

- LMS stable 25.x, Ubuntu 20.04:
# openssl version -a
OpenSSL 1.1.1f  31 Mar 2020
built on: Mon Apr 20 11:53:50 2020 UTC
platform: debian-amd64
options:  bn(64,64) rc4(16x,int) des(int) blowfish(ptr) 
compiler: gcc -fPIC -pthread -m64 -Wa,--noexecstack -Wall -Wa,--noexecstack -g -O2 -fdebug-prefix-map=/build/openssl-P_ODHM/openssl-1.1.1f=. -fstack-protector-strong -Wformat -Werror=format-security -DOPENSSL_TLS_SECURITY_LEVEL=2 -DOPENSSL_USE_NODELETE -DL_ENDIAN -DOPENSSL_PIC -DOPENSSL_CPUID_OBJ -DOPENSSL_IA32_SSE2 -DOPENSSL_BN_ASM_MONT -DOPENSSL_BN_ASM_MONT5 -DOPENSSL_BN_ASM_GF2m -DSHA1_ASM -DSHA256_ASM -DSHA512_ASM -DKECCAK1600_ASM -DRC4_ASM -DMD5_ASM -DAESNI_ASM -DVPAES_ASM -DGHASH_ASM -DECP_NISTZ256_ASM -DX25519_ASM -DPOLY1305_ASM -DNDEBUG -Wdate-time -D_FORTIFY_SOURCE=2
OPENSSLDIR: "/usr/lib/ssl"
ENGINESDIR: "/usr/lib/x86_64-linux-gnu/engines-1.1"
Seeding source: os-specific

Za nowy openssl ?

**Comment by olimplan** [comment]
zapomniałem dodać, że na Ubuntu 18.04 ze stable 24.x plugin działa poprawnie

**Comment by olimplan** [comment]
Dobra, mam rozwiązanie :-) Za nowy openssl, zmienił się domyślny rodzaj szyfrowania na wyższy, SHA1 jest uważane za "passe":
https://stackoverflow.com/questions/58342699/php-curl-curl-error-35-error1414d172ssl-routinestls12-check-peer-sigalgwr
ROZWIĄZANIE
W pliku LMSTauronPowerOutagesPlugin/handlers/TauronPowerOutagesHandler.php zaraz po linijce:
$CURLConnection = curl_init();

dokładamy linijkę:
curl_setopt($CURLConnection, CURLOPT_SSL_CIPHER_LIST, 'DEFAULT@SECLEVEL=1');

a w pliku LMSTauronPowerOutagesPlugin/modules/tauronpoweroutages.php zaraz po linijce:
$ch = curl_init();

dokładamy linijkę:
curl_setopt($ch, CURLOPT_SSL_CIPHER_LIST, 'DEFAULT@SECLEVEL=1');

i wszystko śmiga :-)
