### ISSUE TITLE
Fatal error on line 21  w LMS+ 26.29

### ISSUE THREAD

**Issue by paku2020** [kyob/LMSTauronPowerOutagesPlugin#5]
Hej,
Napotkałem dziś na ten plugin, fajna opcja :)
Instalacja w moim przypadku poszła gładko, dopisałem zmienne w konfiguracji oraz przykładowe dane, 
otrzymuję taki coś 
![image](https://user-images.githubusercontent.com/62469055/122181580-c66ff700-ce89-11eb-94c2-bfd391cefd3b.png)

Czym to może być spowodowane ?

**Comment by kyob** [comment]
Pokaż jakie masz ustawienia, żebym mógł zreplikować problem.

**Comment by paku2020** [comment]
A czego dokładnie ustawienia?
Ustawienia w sekcji tauron zrobiłem tak jak 
https://github.com/kyob/LMSTauronPowerOutagesPlugin/blob/master/configexport-tauron-wartoscglobalna.ini

Problem pojawia się tylko podczas otwarcia strony https://lms/?m=welcome
każda inna zakładka się ładuje tylko że bez odwołania do pluginu tauron w menu lmsa

**Comment by kyob** [comment]
Robiłeś `composer update` ? Czy inne pluginy działają prawidłowo?

**Comment by paku2020** [comment]
Tak, robiłem. 
Robiłem w głównym katalogu jak i w katalogu pluginu.
Inne pluginy z projektu działają poprawnie

**Comment by kyob** [comment]
Czy user apache/nginx ma prawa zapisu do `plugins/LMSTauronPowerOutagesPlugin/tauron.json` ?
Jaka jest zawartość pliku `plugins/LMSTauronPowerOutagesPlugin/tauron.json`?

**Comment by paku2020** [comment]
Dziwne bo nie mam pliku tauron.json

**Comment by kyob** [comment]
Działa?

**Comment by paku2020** [comment]
W jaki sposób wygenerować  plugins/LMSTauronPowerOutagesPlugin/tauron.json ?

**Comment by kyob** [comment]
Sam się generuje. Tylko pewnie nie masz praw zapisu do katalogu `plugins/LMSTauronPowerOutagesPlugin` ?

**Comment by paku2020** [comment]
No to możliwe że nie mam praw,
Podpowiesz jak je nadac ? To od razu bym przetestował

**Comment by kyob** [comment]
Ja mam tak:
```bash
ls -ld LMSTauronPowerOutagesPlugin
drwxr-xr-x 6 apache apache 4096 06-22 14:46 LMSTauronPowerOutagesPlugin
```

**Comment by paku2020** [comment]
u mnie wygląda to tak
`ls -ld LMSTauronPowerOutagesPlugin`
`drwxr-xr-x. 6 root root 4096 Jun 22 12:08 LMSTauronPowerOutagesPlugin`

**Comment by kyob** [comment]
Użytkownik www nie ma dostępu do tego katalogu.
Podstawy się kłaniają: https://www.google.com/search?q=linux+file+and+directory+permissions

**Comment by paku2020** [comment]
Nie wiem czy to do końca jest problem z uprawnieniami, bo inne katalogi w plugins  mają uprawnienia takie same jak te które wysłałem, no i tam działają pluginy, tauron niestety nie działa
