### ISSUE TITLE
Plugin przestał wyświetlać wyłączenia

### ISSUE THREAD

**Issue by olimplan** [kyob/LMSTauronPowerOutagesPlugin#6]
Jakiś czas temu (około miesiąca/dwóch) plugin przestał wyświetlać wyłączenia. Zaktualizowałem u siebie plugin wersją origin master z gita. Po zaciągnięciu zrobiłem composer update, dodałem brakujące ustawienia konfiguracyjne, ustawiłem prawa dostępu do katalogu z pluginem, zrobiłem plik tauron.json (touch taturon.json) z prawami do zapisu przez apacza. Tak wygląda konfiguracja pluginu:
![Screenshot_20230615_134504](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/c5424979-8868-482a-9da1-85bd4caef6b3)
Tak wygląda wynik zadziałania:
![Screenshot_20230615_134837](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/e11a7098-1d6f-4499-9ddd-62ad3d2f44e4)
Po kliknięciu na belkę nic się nie rozwija .... I - co zauważyłem dodatkowo - plugin się nie wyświetla w menu Administracja (poprzednia wersja się wyświetlała):
![Screenshot_20230615_134848](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/b7105385-2dd1-4d18-9214-ea0dcb5d8586)

Plik tauron.json jest pusty ...
W logu apacza jedynie coś takiego:

[Thu Jun 15 13:55:50.921725 2023] [php7:warn] [pid 15226] [client x.x.x.x:35958] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/lms.git/plugins/LMSTauronPowerOutagesPlugin/handlers/TauronPowerOutagesHandler.php on line 79, referer: https://adres_lms/?m=configlist

[Thu Jun 15 13:55:50.921737 2023] [php7:warn] [pid 15226] [client x.x.x.x:35958] PHP Warning:  count(): Parameter must be an array or an object that implements Countable in /var/www/lms.git/plugins/LMSTauronPowerOutagesPlugin/handlers/TauronPowerOutagesHandler.php on line 79, referer: https://adres_lms/?m=configlist

Info na temat wersji LMS, PHP:
![Screenshot_20230615_140207](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/9904ccc5-61d7-4d8c-9a7e-c1c8bca319a2)

**Comment by kyob** [comment]
Niestety tauron przebudował swój system i nie udostępnia już żadnych plików. Szkoda, że nie udostępniają API o wyłączeniach.

**Comment by olimplan** [comment]
Hmm, chyba nie jest tak źle, wyklikałem sobie w formularzu województwo małopolskie, powiat myślenicki (bo ten mnie interesuje), dałem F12 w Firefox i podgląd żądań sieciowych wysyłanych do Tauronu:
![Screenshot_20230615_162941](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/8ad66bbe-0230-488d-a2cd-9a752aa0630a)
i ładnie tam widać zapytanie jquery o JSONa:
![Screenshot_20230615_162958](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/6da11106-99b8-4f4c-bfea-c3d694f4ed9f)
Skopiowałem sobie ten adres, wygląda to tak:
![Screenshot_20230615_163015](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/53d35ff8-2f12-4c48-a6ec-d1f73d7a57ba)
i z tego co widzę, to chyba się po prostu zmieniło zapytanie - trzeba podać provinceGAID i potem districtGAID, jak zawężę do gminy - to na samym końcu się pojawia communeGAID, tutaj przykład:
https://www.tauron-dystrybucja.pl/waapi/outages/area?provinceGAID=12&districtGAID=940&fromDate=2023-06-15T14%3A24%3A34.611Z&toDate=2023-06-20T14%3A24%3A34.611Z&communeGAID=2131&_=1686838943340
To chyba jakieś REST-owe API ;-)
Nie mam pojęcia co oznacza ostatni parametr, ale .... jak sobie skopiujesz ten adres bez tego parametru i wkleisz do przeglądarki, to i tak dostaniesz ładnego JSON-a:
![Screenshot_20230615_163022](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/7b98f9ef-5ea2-474e-a70c-dcfa97968426)
Więc chyba jakaś szansa na dobranie się do tych danych istnieje ;-)
Z tego co widzę, to parametr fromDate lub toDate musi być, bo inaczej w JSONie leci komunikat:
![Screenshot_20230615_164003](https://github.com/kyob/LMSTauronPowerOutagesPlugin/assets/17432641/75e27947-05e1-45a3-ae6a-c7237d31c11b)
Podsumowując - zmienił się adres pod który leci zapytanie i struktura zapytania bo doszły daty from i to oraz numer województwa, ale widzę, że numeracja gmin i powiatów została ta sama ;-) Trzeba sobie tylko zdekodować te numerki z zapytania :-)
Jak coś, służę pomocą testową ;-)

**Comment by olimplan** [comment]
Wrzuciłem pull-requesta ze zmienionym kodem. JSON poprawnie się pobiera już, w pliku ląduje poprawnie ;-) Natomiast zapewne zmieniła się struktura tego JSONa - i tutaj jest jeszcze pole do popisu :-D

**Comment by olimplan** [comment]
Handler poprawiony, przy okazji dodałem parametr z województwem i liczbą dni naprzód do pokazywania planowanych wyłączeń, poprawiłem przekazywane do SMARTY wartości. Została do poprawienia template-ka. Jak będę miał jutro trochę czasu, to spróbuję ogarnąć ;-) Jak się nie wyrobię, to może jakoś w przyszłym tygodniu. Trochę dłubania będzie, bo się zmieniła całkowicie struktura JSON-a a i czas podają w GMT, czyli będzie trzeba przeliczyć ...

**Comment by kyob** [comment]
THX i znowu działa :)

**Comment by olimplan** [comment]
> THX i znowu działa :)

Widzę, że template poprawiłeś szybciutko :-) Zmiany w handlerze zaadoptowałeś, ale nie całkowicie - mój kod uwzględniał brak gminy w zapytaniu (my np. używamy dwa powiaty w konfiguracji, ale nie definiujemy gmin). Po Twojej zmianie jeżeli ktoś nie ma zdefiniowanej gminy to zostanie mu "narzucona" domyślna gmina Knurów, co przy innym województwie i powiecie się nie sprawdzi ;-)

**Comment by kyob** [comment]
Masz rację. Za bardzo skupiłem się na swoim przypadku. Poprawione.
